version: '3.9'

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - app/.env.prod
    depends_on:
      - db
      - mongo

  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env.prod

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - app/.env.prod
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data:
  mongo_data:
  static_volume:
