version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
  web:
    build:
      context: ./app
      dockerfile: Dockerfile_prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - app/.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env.prod

volumes:
  postgres_data:
  static_volume:
